name: Artefact files

on:
  push:
    branches:
      - main

jobs:
  zip-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Zip files
      run: zip -r my-files.zip . -x "*.git*"

    - name: Upload ZIP file as artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-files
        path: my-files.zip
        retention-days: 5

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Upload artifacts to AWS S3
      uses: usualdesigner/s3-artifact-upload@main
      with:
        bucket-name: seunbucket101
        file: my-files.zip    
     