name: Artefact files

on:
  push:
    branches:
      - main

jobs:
  zip-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Generate random number
      id: vars
      run: echo "RANDOM_NUMBER=$(shuf -i 150-200 -n 1)" >> $GITHUB_ENV


    - name: Zip files
      run: zip -r my-files-${{ env.RANDOM_NUMBER }}.zip . -x "*.git*"

    - name: Upload ZIP file as artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-files-${{ env.RANDOM_NUMBER }}
        path: my-files-${{ env.RANDOM_NUMBER }}.zip
        retention-days: 4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Upload artifacts to AWS S3
      uses: usualdesigner/s3-artifact-upload@main
      with:
        bucket-name: seunbucket101
        file: my-files-${{ env.RANDOM_NUMBER }}.zip    
     