name: Deploy master
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
     
    - name: Create ebsrole.json file
      run: |
          echo '{
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Principal": {
                  "Service": "elasticbeanstalk.amazonaws.com"
                },
                "Action": "sts:AssumeRole"
              }
            ]
          }' > ebsrole.json

    - name: Create EBS Role
      run: |
        aws iam create-role --role-name EBSrole1 --assume-role-policy-document file://ebsrole.json
      
    - name: wait for role creation
      run: sleep 5 

    - name: Create ebspolicy.json file
      run: |
        echo '{
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "elasticloadbalancing:DescribeInstanceHealth",
                "elasticloadbalancing:DescribeLoadBalancers",
                "elasticloadbalancing:DescribeTargetHealth",
                "ec2:DescribeInstances",
                "ec2:DescribeInstanceStatus",
                "ec2:GetConsoleOutput",
                "ec2:AssociateAddress",
                "ec2:DescribeAddresses",
                "ec2:DescribeSecurityGroups",
                "sqs:GetQueueAttributes",
                "sqs:GetQueueUrl",
                "autoscaling:DescribeAutoScalingGroups",
                "autoscaling:DescribeAutoScalingInstances",
                "autoscaling:DescribeScalingActivities",
                "autoscaling:DescribeNotificationConfigurations",
                "sns:Publish"
              ],
              "Resource": "*"
            },
            {
              "Effect": "Allow",
              "Action": [
                "logs:DescribeLogStreams",
                "logs:CreateLogStream",
                "logs:PutLogEvents"
              ],
              "Resource": "arn:aws:logs:*:*:log-group:/aws/elasticbeanstalk/*:log-stream:*"
            }
          ]
        }' > ebspolicy.json
        
     
        
    - name: "Create policy"
      run: |
        aws iam create-policy --policy-name ebspolicy1 --policy-document file://ebspolicy.json
        # aws iam create-policy --policy-name ebspolicy2 --policy-document file://ebs2policy.json
  
    - name: wait for policy creation
      run: sleep 6
        
  
    - name: Attach policy to role
      run: |
        aws iam attach-role-policy --role-name EBSrole1 --policy-arn arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:policy/ebspolicy1
        # aws iam attach-role-policy --role-name EBSrole1 --policy-arn arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:policy/ebspolicy2
    - name: wait for policy attachment
      run: sleep 6
          

    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'


    - name: Deploy to AWS Elastic Beanstalk
      uses: Amraneze/aws-beanstalk-deploy@master
      with:
        region: AWS_REGION
        environment_name: class-env
        application_name: books_finder4
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        s3_bucket_name: elasticbeanstalk-us-east-1-675732258064
        s3_file_path: s3://elasticbeanstalk-us-east-1-675732258064/books_finder4/app-0bfa-240703_212052765451.zip
        ebs_version_label: app-787e-240703_204843713461
        ebs_description: ELASTIC_BEANSTALK_DESCRIPTION
        ebs_wait_for_env_to_be_green: true
        updated_version_url: class-env.eba-cequt5fh.us-east-1.elasticbeanstalk.com
        expected_version: app-0bfa-240703_212052765451
        use_same_version: true
        # enable_debug: ${{ secrets.ENABLE_AWS_BS_DEPLOY_DEBUG }}
        