name: Deploy master
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
     
    - name: Create ebsrole.json file
      run: |
          echo '{
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Principal": {
                  "Service": "elasticbeanstalk.amazonaws.com"
                },
                "Action": "sts:AssumeRole"
              }
            ]
          }' > ebsrole.json
          
    - name: Create EBS Role
      run: |
        aws iam create-role --role-name EBSrole --assume-role-policy-document file://ebsrole.json
      
    - name: wait for role creation
      run: sleep 6 
        
    - name: "Create policy"
      run: |
        aws iam create-policy --policy-name ebspolicy --policy-document file://ebspolicy.json
        aws iam create-policy --policy-name ebspolicy2 --policy-document file://ebs2policy.json
  
    - name: wait for policy creation
      run: sleep 8
        
  
    - name: Attach policy to role
      run: |
        aws iam attach-role-policy --role-name ebsrole --policy-arn arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:policy/ebspolicy
        aws iam attach-role-policy --role-name ebsrole --policy-arn arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:policy/ebspolicy2
    - name: wait for policy attachment
      run: sleep 10
          

    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v22
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: books_finder4
        environment_name: class-env
        version_label: app-d2e5-240702_152828665227
        region: us-east-1